### ISSUE TITLE
Integrate with ESLint

### ISSUE THREAD

**Issue by cvburgess** [millermedeiros/esformatter#391] opened 2015-12-15 18:59 UTC
A lot of esformatter's properties are outlined by and overlap with various linters - a good example is ESLint (or JSHint). Is integration with different linters a core functionality, something that should be implemented in a plugin, or not relevant to this project?

**Comment by millermedeiros** [comment] 2016-01-21 04:26
marking as duplicate of #360

**Closed by millermedeiros** 2016-01-21 04:26 UTC
Labels: duplicate, enhancement, feature
