### ISSUE TITLE
Indentation of objects as function arguments

### ISSUE THREAD

**Issue by kewah** [millermedeiros/esformatter#217] opened 2014-10-08 19:50 UTC
Using default config.

Expected:
```
TweenMax.fromTo(el, 0.4, {
  opacity: 1
}, {
  opacity: 0
});
```

Current output:
```
TweenMax.fromTo(el, 0.4, {
  opacity: 1
}, {
    opacity: 0
  });
```

Maybe linked to #201 ?

**Comment by jzaefferer** [comment] 2015-02-16 11:20
Closing as duplicate of #238

**Closed by jzaefferer** 2015-02-16 11:20 UTC
Labels: bug
