### ISSUE TITLE
Chained member indentation and ES6 arrow functions

### ISSUE THREAD

**Issue by kriswill** [millermedeiros/esformatter#363] opened 2015-09-21 03:04 UTC
If you have a promise, where you chain member `.then` and you use an arrow function for the callback, and it returns an naked array `[]` or has a function call with an inline object, it double-indents:

```es6
function makeSomeUsers () {
  const main_user_id = 'f0a000000000000000000001'

  return Account.create({
    username: 'demo-user@test.com',
    password: 'demoaccount',
    owner: main_user_id
  })
    .then(account => User.create({
        id: main_user_id,
        account: account.id,
        firstName: 'Doc',
        lastName: 'Hanks',
        nickname: 'Tom'
      }))
    .then(main_user => User.create([{
        id: 'f0a000000000000000000002',
        firstName: 'John',
        lastName: 'Singleton',
        stats: [0.24, 0.1]
      }, {
        id: 'f0a000000000000000000003',
        firstName: 'Peter',
        lastName: 'Frampton',
        stats: [-0.1, 0.1]
      }, {
        id: 'f0a000000000000000000004',
        firstName: 'Marty',
        lastName: 'McFly',
        stats: [0.44, 0.1]
      }]))
    .then(users => Promise.all([
        User.update(main_user_id, {
          friends: users.map(user => user.id)
        }),
        Group.create({
          id: 'f08000000000000000000001',
          fullName: 'Demo Users',
          stats: [-0.2, 0.15],
          members: [main_user_id].concat(users.map(user => user.id))
        }),
        users
      ]))
    .spread((main_user, group, users) => users)
    .catch(err => console.log('ERROR: ', err))
}
```

Ideally, it would be formatted as:
```es6
function makeSomeUsers () {
  const main_user_id = 'f0a000000000000000000001'

  return Account.create({
    username: 'demo-user@test.com',
    password: 'demoaccount',
    owner: main_user_id
  })
  .then(account => User.create({
    id: main_user_id,
    account: account.id,
    firstName: 'Doc',
    lastName: 'Hanks',
    nickname: 'Tom'
  }))
  .then(main_user => User.create([{
    id: 'f0a000000000000000000002',
    firstName: 'John',
    lastName: 'Singleton',
    stats: [0.24, 0.1]
  }, {
    id: 'f0a000000000000000000003',
    firstName: 'Peter',
    lastName: 'Frampton',
    stats: [-0.1, 0.1]
  }, {
    id: 'f0a000000000000000000004',
    firstName: 'Marty',
    lastName: 'McFly',
    stats: [0.44, 0.1]
  }]))
  .then(users => Promise.all([
    User.update(main_user_id, {
      friends: users.map(user => user.id)
    }),
    Group.create({
      id: 'f08000000000000000000001',
      fullName: 'Demo Users',
      stats: [-0.2, 0.15],
      members: [main_user_id].concat(users.map(user => user.id))
    }),
    users
  ]))
  .spread((main_user, group, users) => users)
  .catch(err => console.log('ERROR: ', err))
}
```
Perhaps an option to control chained-member whitespace indentation as well, `outdent` or `no-indent`.  Personally, I prefer no-indent.

**Comment by ckknight** [comment] 2015-09-24 01:31
Dupe of #357

**Closed** 2015-10-22 06:27 UTC
Labels: duplicate
