### ISSUE TITLE
Formatting replaces React.Component with React . Component

### ISSUE THREAD

**Issue by doque** [millermedeiros/esformatter#370] opened 2015-10-08 13:06 UTC
My config, using Sublime Text 3

    {
        // Format the file when saved
        "format_on_save": false,

        // Path to the node executable, by default it tries to resolve the executable
        // for the command 'node' or 'nodejs'. Change this value to specify your own path
        "nodejs_path": null,

        // EsFormatter specific options
        // default are specified here https://github.com/millermedeiros/esformatter/blob/master/lib/preset/default.json
        "format_options" : {

            // You can change the preset for any other available on ESFormatter
            // Ref: https://github.com/millermedeiros/esformatter/tree/master/lib/preset
            // e.g.: "preset": "jquery"
            "preset": "default",
            "indent": {
                "value": "\t"
            }
        }

    }

Everything is awesome, except this line:

    export default class TimeoutModalComponent extends React.Component {

becomes 

    export default class TimeoutModalComponent extends React . Component {

What flag could cause this issue? It might be a Sublime issue - it doesn't happen when running esformatter from CLI using this config: https://raw.githubusercontent.com/piuccio/sublime-esformatter/master/EsFormatter.sublime-settings

Thanks for your help.

**Comment by millermedeiros** [comment] 2015-10-29 05:23
dupe of #337

**Closed by millermedeiros** 2015-10-29 05:23 UTC
Labels: duplicate
