### ISSUE TITLE
for (x of set) { } formatting

### ISSUE THREAD

**Issue by raggi** [millermedeiros/esformatter#372] opened 2015-10-11 18:06 UTC
The formatting of `for .. of` appears to be broken or at least inconsistent with the formatting of `for .. in`.

Example: http://requirebin.com/embed?gist=0d67452e01754269660f#%7B%22config%22%3A%7B%22jsx%22%3A%7B%22attrsOnSameLineAsTag%22%3Afalse%2C%22maxAttrsOnTag%22%3A1%2C%22firstAttributeOnSameLine%22%3Afalse%2C%22alignWithFirstAttribute%22%3Atrue%7D%7D%2C%22code%22%3A%22for%20(let%20k%20in%20obj)%20%7B%5Cn%20%20%5Cn%7D%5Cn%5Cnfor%20(let%20i%20of%20items)%20%7B%5Cn%20%20%5Cn%7D%22%7D

```
for (let k in obj)
{

}

for (
let i of items)
{

}
```

**Comment by tofagerl** [comment] 2015-10-19 10:05
Same problem here. Ironically the only thing ESlint complains about is that the indentation is wrong...
```
  getById(uuid) {
    const elements = this.getCells();
    for (
    let element of elements){
    if (element.id === uuid) {
      return element;
    }
    }
  }
```

**Comment by millermedeiros** [comment] 2015-10-29 05:19
dupe of #356 (already fixed on master, should release new version soon)

**Closed by millermedeiros** 2015-10-29 05:19 UTC
Labels: bug, duplicate
