### ISSUE TITLE
\n replaced with a new line in template literals

### ISSUE THREAD

**Issue by Mario54** [millermedeiros/esformatter#418] opened 2016-03-15 19:23 UTC
Whenever I use esformatter to format something like this:
```js
console.log(`\n`);
```

the text is transformed into

```js
console.log(`
`);
```

I searched for rules that would lead to this behaviour, but couldn't find any. Is there a way to prevent that from happening?

**Comment by millermedeiros** [comment] 2016-03-17 20:19
duplicate of https://github.com/millermedeiros/esformatter/issues/414 - it's a Babel issue, let's hope they fix it soon: https://phabricator.babeljs.io/T6833

**Closed by millermedeiros** 2016-03-17 20:19 UTC
Labels: bug, duplicate
