### ISSUE TITLE
ES6: Assignment in class

### ISSUE THREAD

**Issue by xotahal** [millermedeiros/esformatter#346] opened 2015-08-05 19:33 UTC
I have problem with this

```javascript
class ClassName {
  arrowTest = () => { return 1; }
  static staticTest = { key: 2 }
}
```

Output:
`//==> Error: Line 2: Unexpected token =`

**Comment by millermedeiros** [comment] 2015-08-05 19:45
duplicate of #345

**Closed by millermedeiros** 2015-08-05 19:45 UTC
Labels: duplicate
