### ISSUE TITLE
After "FunctionName" can not work for methods within object (ES6)

### ISSUE THREAD

**Issue by zhenyong** [millermedeiros/esformatter#464] opened 2016-08-24 03:34 UTC
## Config
```
{
  "root": true,
  "whiteSpace": {
    "after": {
      "FunctionName": 1,
      "FunctionReservedWord": 1
    }
  }
}
```

## Codes

- before

```
function good() {}
var obj = {
  bad() {}
}
```

- after

```
function good () {
}
var obj = {
  bad() {}
}
```

- expect

```
function good () {
}
var obj = {
  bad () {} //!!!! here: space after 'bad'
}
```

I have try to config all option with "1", and nothing help.
Is there any other config can work for my expect? 

I really like esformatter for so much easy config. ^_^

**Comment by millermedeiros** [comment] 2016-08-25 07:54
duplicate of #368

I added a new option called `MethodName` but I still need to release a version!

**Closed by millermedeiros** 2016-08-25 07:54 UTC
Labels: duplicate
