### ISSUE TITLE
Odd indentation for arrays of objects

### ISSUE THREAD

**Issue by nathanboktae** [millermedeiros/esformatter#262] opened 2015-03-05 07:13 UTC
Input with defaults:
```
var model = [{ name: 'bob' }, { name: 'Jane' }]
```

Actual output:
```
var model = [{
  name: 'bob'
  }, {
  name: 'Jane'
}]
```

"expected" output:
```
var model = [{
  name: 'bob'
}, {
  name: 'Jane'
}]
```

or

```
var model = [{
    name: 'bob'
  }, {
    name: 'Jane'
  }]
```

It appears impossible for me to configure the options to achieve either of the expected outputs.

**Comment by kewah** [comment] 2015-03-05 08:36
Which esformatter version do you use ? 
I get the expected output using v0.5.0

**Comment by millermedeiros** [comment] 2015-03-05 14:25
marking as a duplicate of #224 please reopen if the bug still exists on v0.5.0 (it should not happen based on the tests we added at https://github.com/millermedeiros/esformatter/commit/957cb3c2a3abf33e022dc03106e1b052be01abdf)

**Closed by millermedeiros** 2015-03-05 14:25 UTC
Labels: duplicate

**Comment by nathanboktae** [comment] 2015-03-05 17:27
My bad, it does work on 0.5.0. both [piuccio/sublime-esformatter](https://github.com/piuccio/sublime-esformatter) and (esformatter visualizer)[http://lloiser.github.io/esformatter-visualize/] are on an older version with this issue.

I've been watching this project for over a year now - great to see how far it's come along! Time to write a plugin.

**Comment by millermedeiros** [comment] 2015-03-05 20:26
@nathanboktae I added a PR to esformatter-visualize and created a new issue on sublime-esformatter. thanks!
