### ISSUE TITLE
RequireBin live demo erases config text while typing

### ISSUE THREAD

**Issue by Asuza** [millermedeiros/esformatter#381] opened 2015-11-04 16:06 UTC
I'm using the (very helpful) live formatter on RequireBin in order to get my initial config ready, but when I type in the "Config" area, the cursor works more like an Overwrite than an Insert. Whatever I type replaces what is ahead of it.

If I have the following:
```json
    "VariableDeclaration": ">=1",
```
Then place my cursor after the "1", and type <kbd>Backspace</kbd> then <kbd>2</kbd>, I'll end up with:
```json
    "VariableDeclaration": ">=2,
```
Which breaks the config.

**Comment by Asuza** [comment] 2015-11-04 18:15
I was able to fix the issue by pushing <kbd>Insert</kbd>... leaving the issue open since there's no indicator of the typing mode, and I'm still not certain if I accidentally put the editor into Overwrite mode or if it started out that way.

**Comment by millermedeiros** [comment] 2016-01-21 04:34
**TODO:** improve live demo! it was created by the [esformatter-jsx plugin](https://github.com/royriojas/esformatter-jsx) and it doesn't even use our default settings..

marking as duplicate of #43

**Closed by millermedeiros** 2016-01-21 04:34 UTC
Labels: enhancement
