### ISSUE TITLE
Indentation of function body as method argument

### ISSUE THREAD

**Issue by piuccio** [millermedeiros/esformatter#227] opened 2014-11-18 12:44 UTC
Maybe related to #217 

source
```js
define([
  'banana',
  'pear'
], function (
  banana,
  pear
) {
  banana.blendWith(pear);
})
```

formatted
```js
define([
  'banana',
  'pear'
], function(
  banana,
  pear
  ) {
    banana.blendWith(pear);
  })
```

Expected simply not to be formatted

**Comment by jzaefferer** [comment] 2015-02-16 11:20
Closing as duplicate of #238

**Closed by jzaefferer** 2015-02-16 11:20 UTC
Labels: bug
